### PR TITLE
update screen shots with Plone 5.0.7

### PR DESCRIPTION
**Pull request by tkimnguyen**
for https://github.com/collective/collective.newsticker/issues/26

### CODE REVIEW

**Comment by hvelarde** [comment]
you have to update the dimensions of the images on the README file also; do you mind using the horizontal toolbar on the screenshot?

**Comment by tkimnguyen** [comment]
Ah sorry I will change the dimensions. Re horizontal you prefer the non-default position of the toolbar? ;)

**Comment by tkimnguyen** [comment]
Will get to this later today

**Comment by tkimnguyen** [comment]
ok done @hvelarde !

**Comment by hvelarde** [comment]
thanks!

**Pull request merged**
